title: Kayla Duskin
name: Kayla Duskin
description: PhD candidate at University of Washington
email: kduskin[at]uw.edu
github_username: kduskin
linkedin_username: kayla-duskin
scholar_username: 6EsQFT8AAAAJ
url: "https://kduskin.github.io"


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  papers:
    output: true
    permalink: /papers/:path/ 