title: Kayla Duskin
name: Kayla Duskin
description: PhD candidate at University of Washington
previous: Pacific Northwest National Lab
email: kduskin@uw.edu
github_username: kduskin
linkedin_username: kayla-duskin
scholar_username: 6EsQFT8AAAAJ

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  papers:
    output: true
    permalink: /papers/:path/ 